name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: action-test
      id: atest
      uses: romanprog/megaaction@master
      with:
        helo-name: 'Arti'